/* Nordik Store catalogue: categories, collections and products with their options. */
(function buildNordikCatalog() {
  const UNSPLASH_BASE_URL = "https://images.unsplash.com/photo-";
  function buildImageUrl(photoId, imageOptions = {}) {
    const imageWidth = imageOptions.width || 1200;
    const heightParameter = imageOptions.height ? `&h=${imageOptions.height}` : "";
    const focalParameters = imageOptions.zoom ? `&crop=focalpoint&fp-x=${imageOptions.focusX}&fp-y=${imageOptions.focusY}&fp-z=${imageOptions.zoom}` : "";
    return `${UNSPLASH_BASE_URL}${photoId}?auto=format&fit=crop&w=${imageWidth}${heightParameter}&q=80${focalParameters}`;
  }
  const categories = [
    { id: "luminaires", name: "Luminaires", tagline: "Une lumière douce pour les longues soirées", photoId: "1522771739844-6a9f6d5f14af" },
    { id: "ceramique", name: "Céramique", tagline: "Pièces tournées à la main, émaux mats", photoId: "1610701596007-11502861dcfa" },
    { id: "textiles", name: "Textiles", tagline: "Laine, lin et coton biologique", photoId: "1579656381226-5fc0f0100c3b" },
    { id: "mobilier", name: "Mobilier", tagline: "Bois clair, lignes pures, fait pour durer", photoId: "1586023492125-27b2c045efd7" }
  ];
  const ambiancePhotoIds = ["1616486338812-3dadae4b4ace", "1493663284031-b7e3aefcae8e", "1519710164239-da123dc03ef4", "1556020685-ae41abfc9365", "1513694203232-719a280e022f", "1524758631624-e2822e304c36"];
  const colorPalette = {
    neige: { name: "Blanc neige", hex: "#f4f2ee" },
    ardoise: { name: "Gris ardoise", hex: "#5d6468" },
    nuit: { name: "Noir nuit", hex: "#1f2326" },
    sauge: { name: "Vert sauge", hex: "#8fa392" },
    sapin: { name: "Vert sapin", hex: "#2f4a3d" },
    sable: { name: "Sable", hex: "#d8c7a8" },
    argile: { name: "Argile", hex: "#c17f59" },
    chene: { name: "Chêne naturel", hex: "#c9a77c" },
    noyer: { name: "Noyer", hex: "#6b4a33" },
    menthe: { name: "Menthe givrée", hex: "#a9e0d6" },
    brume: { name: "Bleu brume", hex: "#9fb3c2" },
    cognac: { name: "Cognac", hex: "#9a5a32" }
  };
  const pickColors = (...colorKeys) => colorKeys.map((colorKey) => colorPalette[colorKey]);
  const products = [
    { id: "lampadaire-fjord", name: "Lampadaire Fjord", category: "luminaires", price: 189, compareAtPrice: 229, photoId: "1507473885765-e6ed057f782c", focus: [0.62, 0.3], colors: pickColors("ardoise", "neige", "nuit"), sizes: [], designer: "Studio Lind, Copenhague", rating: 4.8, reviewCount: 126, bestseller: true, isNew: false, stock: 14, description: "Un lampadaire liseuse à l'abat-jour orientable, pensé pour éclairer un fauteuil sans éblouir. Son pied en acier laqué et sa tête pivotante en font le compagnon idéal des lectures d'hiver.", details: ["Acier laqué époxy, finition mate", "Hauteur 152 cm, abat-jour Ø 24 cm", "Culot E27, ampoule LED 8 W fournie", "Interrupteur à pied, câble textile 2 m"] },
    { id: "suspension-halo", name: "Suspension Halo", category: "luminaires", price: 129, compareAtPrice: null, photoId: "1513506003901-1e6a229e2d15", focus: [0.5, 0.45], colors: pickColors("neige", "ardoise", "sapin"), sizes: [{ label: "Ø 30 cm", priceDelta: 0 }, { label: "Ø 40 cm", priceDelta: 30 }], designer: "Atelier Hedda, Oslo", rating: 4.7, reviewCount: 84, bestseller: true, isNew: false, stock: 22, description: "Une suspension en dôme au profil tendu qui diffuse une lumière chaude et dirigée. Parfaite au-dessus d'une table à manger ou d'un îlot de cuisine.", details: ["Aluminium repoussé, intérieur blanc réfléchissant", "Câble textile réglable jusqu'à 150 cm", "Culot E27, compatible variateur", "Rosace de plafond assortie incluse"] },
    { id: "lampe-chevet-lys", name: "Lampe de chevet Lys", category: "luminaires", price: 89, compareAtPrice: null, photoId: "1522771739844-6a9f6d5f14af", focus: [0.82, 0.38], colors: pickColors("nuit", "sable"), sizes: [], designer: "Studio Lind, Copenhague", rating: 4.6, reviewCount: 57, bestseller: false, isNew: true, stock: 9, description: "Une silhouette fine en métal noir et une ampoule apparente à filament : la lampe Lys apporte une touche graphique à la chambre et une lumière tamisée pour s'endormir sereinement.", details: ["Métal brossé et base en chêne massif", "Hauteur 46 cm", "Ampoule filament LED 4 W, 2200 K", "Variateur tactile trois intensités"] },
    { id: "tasses-skog", name: "Set de 4 tasses Skog", category: "ceramique", price: 48, compareAtPrice: null, photoId: "1610701596007-11502861dcfa", focus: [0.5, 0.6], colors: pickColors("neige", "sable"), sizes: [], designer: "Keramik Ulla, Göteborg", rating: 4.9, reviewCount: 212, bestseller: true, isNew: false, stock: 40, description: "Quatre tasses en grès moucheté, émail satiné à l'intérieur et base brute laissée nue pour révéler la terre. Chaque pièce est unique et légèrement différente des autres.", details: ["Grès émaillé, tourné à la main", "Contenance 25 cl", "Compatibles lave-vaisselle et micro-ondes", "Vendues par lot de quatre"] },
    { id: "vase-mjolk", name: "Vase Mjölk", category: "ceramique", price: 64, compareAtPrice: null, photoId: "1612196808214-b8e1d6145a8c", focus: [0.5, 0.6], colors: pickColors("neige", "sable", "argile"), sizes: [{ label: "S · 18 cm", priceDelta: 0 }, { label: "M · 26 cm", priceDelta: 18 }, { label: "L · 34 cm", priceDelta: 36 }], designer: "Keramik Ulla, Göteborg", rating: 4.8, reviewCount: 98, bestseller: true, isNew: false, stock: 18, description: "Une panse généreuse et un col resserré : le vase Mjölk sublime une simple branche d'eucalyptus ou des graminées séchées. Son émail coquille d'œuf capte la lumière avec délicatesse.", details: ["Grès émaillé mat", "Étanche, convient aux fleurs fraîches", "Trois tailles disponibles", "Fabriqué en Suède"] },
    { id: "duo-vases-natt", name: "Duo de vases Natt", category: "ceramique", price: 72, compareAtPrice: 86, photoId: "1565193566173-7a0ee3dbe261", focus: [0.55, 0.65], colors: pickColors("ardoise", "neige"), sizes: [], designer: "Formhus, Aarhus", rating: 4.5, reviewCount: 41, bestseller: false, isNew: false, stock: 12, description: "Deux bouteilles élancées aux hauteurs complémentaires, à disposer sur une console ou un rebord de fenêtre. Leur teinte minérale s'accorde aux intérieurs sombres comme aux murs blancs.", details: ["Céramique émaillée mate", "Hauteurs 22 cm et 30 cm", "Usage décoratif et fleurs séchées", "Vendus par deux"] },
    { id: "cache-pot-tundra", name: "Cache-pot Tundra", category: "ceramique", price: 34, compareAtPrice: null, photoId: "1485955900006-10f4d324d411", focus: [0.5, 0.7], colors: pickColors("menthe", "neige", "brume"), sizes: [{ label: "Ø 12 cm", priceDelta: 0 }, { label: "Ø 16 cm", priceDelta: 8 }], designer: "Formhus, Aarhus", rating: 4.7, reviewCount: 133, bestseller: false, isNew: true, stock: 35, description: "Un cache-pot aux couleurs douces pour habiller vos plantes grasses et succulentes. Sa forme légèrement conique lui donne une allure à la fois rétro et contemporaine.", details: ["Grès émaillé brillant", "Soucoupe intégrée amovible", "Convient aux pots de culture standard", "Fabriqué au Portugal"] },
    { id: "coupe-sand", name: "Coupe Sand", category: "ceramique", price: 42, compareAtPrice: null, photoId: "1603204077779-bed963ea7d0e", focus: [0.5, 0.6], colors: pickColors("sable", "neige"), sizes: [], designer: "Keramik Ulla, Göteborg", rating: 4.4, reviewCount: 26, bestseller: false, isNew: true, stock: 7, description: "Une coupe basse au bord irrégulier, idéale pour composer un jardin miniature de cactus ou accueillir fruits et clés dans l'entrée.", details: ["Grès chamotté, émail sable", "Ø 28 cm, hauteur 9 cm", "Lavage à la main recommandé", "Pièce unique, nuances variables"] },
    { id: "coussin-hygge", name: "Coussin Hygge", category: "textiles", price: 39, compareAtPrice: null, photoId: "1584100936595-c0654b55a2e2", focus: [0.5, 0.6], colors: pickColors("neige", "sable", "sauge"), sizes: [{ label: "40 × 40 cm", priceDelta: 0 }, { label: "50 × 50 cm", priceDelta: 6 }, { label: "60 × 60 cm", priceDelta: 12 }], designer: "Väv Studio, Malmö", rating: 4.8, reviewCount: 187, bestseller: true, isNew: false, stock: 60, description: "Un coussin moelleux garni de plumes recyclées, à la housse en lin lavé au toucher froissé. La base indispensable pour un canapé où l'on a envie de s'attarder.", details: ["Housse 100 % lin lavé, fermeture invisible", "Garnissage plumes recyclées", "Housse lavable à 40 °C", "Certifié OEKO-TEX"] },
    { id: "plaid-lofoten", name: "Plaid Lofoten", category: "textiles", price: 79, compareAtPrice: 95, photoId: "1579656381226-5fc0f0100c3b", focus: [0.35, 0.55], colors: pickColors("neige", "sable", "ardoise"), sizes: [], designer: "Väv Studio, Malmö", rating: 4.9, reviewCount: 164, bestseller: true, isNew: false, stock: 25, description: "Tissé en laine d'agneau et finitions à franges, le plaid Lofoten se jette sur un lit ou un fauteuil et réchauffe instantanément la pièce comme les soirées.", details: ["80 % laine d'agneau, 20 % coton bio", "130 × 180 cm", "Nettoyage à sec ou lavage laine 30 °C", "Tissé au Danemark"] },
    { id: "tapis-saga", name: "Tapis Saga", category: "textiles", price: 249, compareAtPrice: null, photoId: "1600166898405-da9535204843", focus: [0.5, 0.5], colors: pickColors("sable", "brume"), sizes: [{ label: "160 × 230 cm", priceDelta: 0 }, { label: "200 × 300 cm", priceDelta: 140 }], designer: "Väv Studio, Malmö", rating: 4.6, reviewCount: 52, bestseller: false, isNew: false, stock: 6, description: "Un tapis tissé plat aux motifs délavés inspirés des tapis anciens. Son velours ras se marie avec un parquet clair et supporte les pièces à fort passage.", details: ["Laine et viscose, tissage plat", "Épaisseur 8 mm", "Sous-tapis antidérapant conseillé", "Aspiration sans brosse rotative"] },
    { id: "tabouret-ask", name: "Tabouret Ask", category: "mobilier", price: 119, compareAtPrice: null, photoId: "1503602642458-232111445657", focus: [0.5, 0.4], colors: pickColors("chene", "neige"), sizes: [{ label: "Assise 45 cm", priceDelta: 0 }, { label: "Bar 75 cm", priceDelta: 30 }], designer: "Snickeri Berg, Uppsala", rating: 4.7, reviewCount: 73, bestseller: false, isNew: false, stock: 16, description: "Assise en frêne, piètement à barreaux : le tabouret Ask est un classique de l'atelier suédois. Il sert de siège d'appoint, de table de chevet ou de sellette pour une plante.", details: ["Frêne massif huilé", "Charge maximale 120 kg", "Livré monté", "Bois issu de forêts certifiées FSC"] },
    { id: "chaise-alva", name: "Chaise Alva", category: "mobilier", price: 159, compareAtPrice: 179, photoId: "1517705008128-361805f42e86", focus: [0.5, 0.55], colors: pickColors("neige", "sauge", "nuit"), sizes: [], designer: "Studio Lind, Copenhague", rating: 4.8, reviewCount: 145, bestseller: true, isNew: false, stock: 30, description: "Une coque enveloppante en polypropylène recyclé posée sur un piètement en chêne. Confortable sans coussin, la chaise Alva s'invite autour de la table comme au bureau.", details: ["Coque en polypropylène 100 % recyclé", "Pieds en chêne massif", "Hauteur d'assise 45 cm", "Empilable par deux"] },
    { id: "tabouret-sten", name: "Tabouret de bar Sten", category: "mobilier", price: 139, compareAtPrice: null, photoId: "1581539250439-c96689b516dd", focus: [0.5, 0.35], colors: pickColors("nuit", "neige"), sizes: [{ label: "Comptoir 65 cm", priceDelta: 0 }, { label: "Bar 75 cm", priceDelta: 10 }], designer: "Formhus, Aarhus", rating: 4.5, reviewCount: 38, bestseller: false, isNew: false, stock: 11, description: "Coque noire mate, repose-pieds en acier et pieds en hêtre : le tabouret Sten donne un caractère affirmé à un îlot de cuisine ou à un bar.", details: ["Coque polypropylène, pieds hêtre massif", "Repose-pieds acier laqué noir", "Patins de protection fournis", "Assemblage en 10 minutes"] },
    { id: "chaise-noa", name: "Chaise Noa", category: "mobilier", price: 145, compareAtPrice: null, photoId: "1592078615290-033ee584e267", focus: [0.45, 0.5], colors: pickColors("nuit", "neige", "brume"), sizes: [], designer: "Studio Lind, Copenhague", rating: 4.6, reviewCount: 64, bestseller: false, isNew: true, stock: 20, description: "La chaise Noa associe une assise rembourrée en simili cuir à un piètement en hêtre légèrement évasé. Un confort généreux pour les dîners qui s'éternisent.", details: ["Assise rembourrée, revêtement sans PVC", "Pieds en hêtre massif teinté", "Hauteur d'assise 46 cm", "Vendue à l'unité"] },
    { id: "fauteuil-moln", name: "Fauteuil Moln", category: "mobilier", price: 429, compareAtPrice: null, photoId: "1567538096630-e0c55bd6374c", focus: [0.5, 0.5], colors: pickColors("neige", "sable"), sizes: [], designer: "Atelier Hedda, Oslo", rating: 4.9, reviewCount: 49, bestseller: false, isNew: true, stock: 5, description: "Capitonné comme un nuage, le fauteuil Moln enveloppe avec douceur. Son tissu bouclé ivoire et ses pieds galbés apportent une note poétique à la chambre ou au salon.", details: ["Tissu bouclette 100 % polyester recyclé", "Structure en hêtre, mousse haute résilience", "L 68 × P 70 × H 82 cm", "Livraison en pièce de vie offerte"] },
    { id: "canape-granskog", name: "Canapé Granskog", category: "mobilier", price: 1290, compareAtPrice: 1490, photoId: "1555041469-a586c61ea9bc", focus: [0.5, 0.55], colors: pickColors("sapin", "sable", "brume"), sizes: [{ label: "3 places", priceDelta: 0 }, { label: "4 places", priceDelta: 310 }], designer: "Atelier Hedda, Oslo", rating: 4.8, reviewCount: 92, bestseller: true, isNew: false, stock: 4, description: "Un velours profond, des lignes tendues et des pieds fuselés en chêne : le canapé Granskog est la pièce maîtresse d'un salon chaleureux. Ses coussins déhoussables se lavent facilement.", details: ["Velours côtelé fin, housses déhoussables", "Structure bois massif garantie 10 ans", "Assise ressorts ensachés et mousse", "Livraison en pièce de vie et installation offertes"] },
    { id: "canape-ljung", name: "Canapé Ljung", category: "mobilier", price: 1490, compareAtPrice: null, photoId: "1540574163026-643ea20ade25", focus: [0.5, 0.5], colors: pickColors("cognac", "nuit"), sizes: [{ label: "3 places", priceDelta: 0 }, { label: "Angle", priceDelta: 520 }], designer: "Snickeri Berg, Uppsala", rating: 4.7, reviewCount: 35, bestseller: false, isNew: false, stock: 3, description: "Un cuir pleine fleur au tannage végétal qui se patine magnifiquement avec les années. Le canapé Ljung offre une assise profonde et des accoudoirs larges pour poser un plateau.", details: ["Cuir pleine fleur, tannage végétal", "Structure hêtre et contreplaqué", "Profondeur d'assise 60 cm", "Fabriqué en Suède, garantie 10 ans"] },
    { id: "console-ek", name: "Console Ek", category: "mobilier", price: 349, compareAtPrice: null, photoId: "1532372320572-cda25653a26d", focus: [0.4, 0.65], colors: pickColors("chene", "noyer"), sizes: [], designer: "Snickeri Berg, Uppsala", rating: 4.6, reviewCount: 22, bestseller: false, isNew: false, stock: 8, description: "Une console aux angles adoucis, taillée dans un chêne massif aux veines marquées. Sa tablette basse accueille livres et paniers, son plateau les objets du quotidien.", details: ["Chêne massif huilé", "L 110 × P 35 × H 78 cm", "Tablette inférieure fixe", "Assemblage tenon-mortaise"] }
  ];
  products.forEach((product, productIndex) => {
    const [focusX, focusY] = product.focus;
    product.ambiancePhotoId = ambiancePhotoIds[productIndex % ambiancePhotoIds.length];
    product.image = buildImageUrl(product.photoId, { width: 900, height: 1100 });
    product.thumbnail = buildImageUrl(product.photoId, { width: 480, height: 600 });
    product.hoverImage = buildImageUrl(product.photoId, { width: 480, height: 600, focusX, focusY, zoom: 1.7 });
    product.gallery = [
      { src: buildImageUrl(product.photoId, { width: 1200, height: 1400 }), alt: `${product.name}, vue d'ensemble` },
      { src: buildImageUrl(product.photoId, { width: 1200, height: 1400, focusX, focusY, zoom: 2 }), alt: `${product.name}, détail des finitions` },
      { src: buildImageUrl(product.ambiancePhotoId, { width: 1200, height: 1400 }), alt: `${product.name} en situation dans un intérieur scandinave` },
      { src: buildImageUrl(product.photoId, { width: 1200, height: 1400, focusX: Math.min(focusX + 0.1, 0.9), focusY: Math.max(focusY - 0.1, 0.1), zoom: 3 }), alt: `${product.name}, gros plan sur la matière` }
    ];
  });
  window.NordikCatalog = {
    buildImageUrl,
    categories,
    products,
    getProductById: (productId) => products.find((product) => product.id === productId) || null,
    getCategoryById: (categoryId) => categories.find((category) => category.id === categoryId) || null,
    getUnitPrice: (product, sizeLabel) => {
      const selectedSize = product.sizes.find((size) => size.label === sizeLabel);
      return product.price + (selectedSize ? selectedSize.priceDelta : 0);
    }
  };
})();
